const { HTMLField, SchemaField, NumberField, StringField, FilePathField, ArrayField, BooleanField } =
  foundry.data.fields;

export class FollowerData extends foundry.abstract.TypeDataModel {
  static defineSchema() {
    const requiredInteger = { required: true, nullable: false, integer: true };
    return {
      hp: new SchemaField({
        value: new NumberField({ ...requiredInteger, min: 0, initial: 10 }),
        min: new NumberField({ ...requiredInteger, min: 0, initial: 10 }),
        max: new NumberField({ ...requiredInteger, min: 0, initial: 10 }),
        adj: new NumberField({ ...requiredInteger, min: 0, initial: 10 }),
      }),
      stats: new SchemaField({
        siz: new SchemaField({
          value: new NumberField({ ...requiredInteger, min: 0, initial: 10 }),
          culture: new NumberField({ ...requiredInteger, initial: 10 }),
          create: new NumberField({ ...requiredInteger, initial: 10 }),
          poison: new NumberField({ ...requiredInteger, initial: 10 }),
          disease: new NumberField({ ...requiredInteger, initial: 10 }),
          sol: new NumberField({ ...requiredInteger, initial: 10 }),
          age: new NumberField({ ...requiredInteger, initial: 10 }),
          major: new NumberField({ ...requiredInteger, initial: 10 }),
          winter: new NumberField({ ...requiredInteger, initial: 10 }),
          growth: new NumberField({ ...requiredInteger, initial: 10 }),
          formula: new StringField({ required: false }),
        }),
        dex: new SchemaField({
          value: new NumberField({ ...requiredInteger, min: 0, initial: 10 }),
          culture: new NumberField({ ...requiredInteger, initial: 10 }),
          create: new NumberField({ ...requiredInteger, initial: 10 }),
          poison: new NumberField({ ...requiredInteger, initial: 10 }),
          disease: new NumberField({ ...requiredInteger, initial: 10 }),
          sol: new NumberField({ ...requiredInteger, initial: 10 }),
          age: new NumberField({ ...requiredInteger, initial: 10 }),
          major: new NumberField({ ...requiredInteger, initial: 10 }),
          winter: new NumberField({ ...requiredInteger, initial: 10 }),
          growth: new NumberField({ ...requiredInteger, initial: 10 }),
          formula: new StringField({ required: false }),
        }),
        str: new SchemaField({
          value: new NumberField({ ...requiredInteger, min: 0, initial: 10 }),
          culture: new NumberField({ ...requiredInteger, initial: 10 }),
          create: new NumberField({ ...requiredInteger, initial: 10 }),
          poison: new NumberField({ ...requiredInteger, initial: 10 }),
          disease: new NumberField({ ...requiredInteger, initial: 10 }),
          sol: new NumberField({ ...requiredInteger, initial: 10 }),
          age: new NumberField({ ...requiredInteger, initial: 10 }),
          major: new NumberField({ ...requiredInteger, initial: 10 }),
          winter: new NumberField({ ...requiredInteger, initial: 10 }),
          growth: new NumberField({ ...requiredInteger, initial: 10 }),
          formula: new StringField({ required: false }),
        }),
        con: new SchemaField({
          value: new NumberField({ ...requiredInteger, min: 0, initial: 10 }),
          culture: new NumberField({ ...requiredInteger, initial: 10 }),
          create: new NumberField({ ...requiredInteger, initial: 10 }),
          poison: new NumberField({ ...requiredInteger, initial: 10 }),
          disease: new NumberField({ ...requiredInteger, initial: 10 }),
          sol: new NumberField({ ...requiredInteger, initial: 10 }),
          age: new NumberField({ ...requiredInteger, initial: 10 }),
          major: new NumberField({ ...requiredInteger, initial: 10 }),
          winter: new NumberField({ ...requiredInteger, initial: 10 }),
          growth: new NumberField({ ...requiredInteger, initial: 10 }),
          formula: new StringField({ required: false }),
        }),
        app: new SchemaField({
          value: new NumberField({ ...requiredInteger, min: 0, initial: 10 }),
          culture: new NumberField({ ...requiredInteger, initial: 10 }),
          create: new NumberField({ ...requiredInteger, initial: 10 }),
          poison: new NumberField({ ...requiredInteger, initial: 10 }),
          disease: new NumberField({ ...requiredInteger, initial: 10 }),
          sol: new NumberField({ ...requiredInteger, initial: 10 }),
          age: new NumberField({ ...requiredInteger, initial: 10 }),
          major: new NumberField({ ...requiredInteger, initial: 10 }),
          winter: new NumberField({ ...requiredInteger, initial: 10 }),
          growth: new NumberField({ ...requiredInteger, initial: 10 }),
          formula: new StringField({ required: false }),
        }),
      }),
      subtype: new StringField({ required: true, blank: true, initial: "squire" }),
      description: new HTMLField({ required: true, blank: true, initial: "" }),
      sol: new StringField({ required: true, blank: true, initial: "ordinary" }),
      woundTotal: new NumberField({ ...requiredInteger, initial: 0 }),
      manMove: new NumberField({ ...requiredInteger, initial: 0 }),
      manArm: new NumberField({ ...requiredInteger, initial: 0 }),
      manShd: new NumberField({ ...requiredInteger, initial: 0 }),
      manMaxHP: new NumberField({ ...requiredInteger, initial: 0 }),
      manKnockdown: new NumberField({ ...requiredInteger, initial: 0 }),
      manMjrWnd: new NumberField({ ...requiredInteger, initial: 0 }),
      manDmg: new NumberField({ ...requiredInteger, initial: 0 }),
      manHealRate: new NumberField({ ...requiredInteger, initial: 0 }),
      manUnconscious: new NumberField({ ...requiredInteger, initial: 0 }),
      squire: new NumberField({ ...requiredInteger, initial: 0 }),
      born: new NumberField({ ...requiredInteger, initial: 487 }),
      culture: new StringField({ required: true, blank: true, initial: "" }),
      religion: new StringField({ required: true, blank: true, initial: "" }),
      homeland: new StringField({ required: true, blank: true, initial: "" }),
      family: new StringField({ required: true, blank: true, initial: "" }),
      features: new StringField({ required: true, blank: true, initial: "" }),
      heir: new BooleanField({ initial: false }),
      lock: new BooleanField({ initial: false }),
      barren: new BooleanField({ initial: false }),
      view: new BooleanField({ initial: false }),
    };
  }
}
